apiVersion: v1
kind: ConfigMap
metadata:
  name: store-config
  namespace: dev
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5433/store"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE: "10"
  LOGGING_LEVEL_COM_EXAMPLE_STORE: "DEBUG"
  APP_SECURITY_CORS_ORIGIN: "http://localhost:3000"
