spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/store}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      leak-detection-threshold: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: StoreHikariPool
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
        use_sql_comments: ${SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS:false}
        default_batch_fetch_size: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE:20}
        jdbc:
          batch_size: 30
        order_inserts: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    com.example.store: ${LOGGING_LEVEL_COM_EXAMPLE_STORE:INFO}
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
