apiVersion: v1
kind: ConfigMap
metadata:
  name: store-config
  namespace: prod
data:
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE: "20"
  LOGGING_LEVEL_COM_EXAMPLE_STORE: "INFO"
