-- Product seed data
INSERT INTO product (id, description) VALUES (1, 'Wireless Bluetooth Headphones');
INSERT INTO product (id, description) VALUES (2, 'USB-C Charging Cable');
INSERT INTO product (id, description) VALUES (3, 'Mechanical Keyboard');
INSERT INTO product (id, description) VALUES (4, 'Ergonomic Mouse');
INSERT INTO product (id, description) VALUES (5, '27-inch Monitor');
INSERT INTO product (id, description) VALUES (6, 'Laptop Stand');
INSERT INTO product (id, description) VALUES (7, 'Webcam HD 1080p');
INSERT INTO product (id, description) VALUES (8, 'Noise Cancelling Earbuds');
INSERT INTO product (id, description) VALUES (9, 'Portable SSD 1TB');
INSERT INTO product (id, description) VALUES (10, 'Wireless Charger Pad');
INSERT INTO product (id, description) VALUES (11, 'Smart Watch');
INSERT INTO product (id, description) VALUES (12, 'Fitness Tracker Band');
INSERT INTO product (id, description) VALUES (13, 'Phone Case Leather');
INSERT INTO product (id, description) VALUES (14, 'Screen Protector Glass');
INSERT INTO product (id, description) VALUES (15, 'Power Bank 20000mAh');
INSERT INTO product (id, description) VALUES (16, 'HDMI Cable 2m');
INSERT INTO product (id, description) VALUES (17, 'Desk Lamp LED');
INSERT INTO product (id, description) VALUES (18, 'Office Chair');
INSERT INTO product (id, description) VALUES (19, 'Standing Desk');
INSERT INTO product (id, description) VALUES (20, 'Monitor Arm Mount');
INSERT INTO product (id, description) VALUES (21, 'Cable Management Kit');
INSERT INTO product (id, description) VALUES (22, 'Mousepad XL');
INSERT INTO product (id, description) VALUES (23, 'USB Hub 7-Port');
INSERT INTO product (id, description) VALUES (24, 'External DVD Drive');
INSERT INTO product (id, description) VALUES (25, 'Laptop Backpack');
INSERT INTO product (id, description) VALUES (26, 'Tablet Stylus Pen');
INSERT INTO product (id, description) VALUES (27, 'Wireless Presenter');
INSERT INTO product (id, description) VALUES (28, 'Webcam Ring Light');
INSERT INTO product (id, description) VALUES (29, 'Microphone USB Condenser');
INSERT INTO product (id, description) VALUES (30, 'Headphone Stand');
INSERT INTO product (id, description) VALUES (31, 'Keyboard Wrist Rest');
INSERT INTO product (id, description) VALUES (32, 'Anti-Glare Screen Filter');
INSERT INTO product (id, description) VALUES (33, 'Ethernet Cable Cat6 5m');
INSERT INTO product (id, description) VALUES (34, 'Wi-Fi Router Mesh');
INSERT INTO product (id, description) VALUES (35, 'Network Switch 8-Port');
INSERT INTO product (id, description) VALUES (36, 'Surge Protector Strip');
INSERT INTO product (id, description) VALUES (37, 'UPS Battery Backup');
INSERT INTO product (id, description) VALUES (38, 'Thermal Paste');
INSERT INTO product (id, description) VALUES (39, 'Compressed Air Duster');
INSERT INTO product (id, description) VALUES (40, 'Anti-Static Wrist Strap');
INSERT INTO product (id, description) VALUES (41, 'Graphics Card RTX');
INSERT INTO product (id, description) VALUES (42, 'RAM DDR5 16GB');
INSERT INTO product (id, description) VALUES (43, 'NVMe SSD 2TB');
INSERT INTO product (id, description) VALUES (44, 'CPU Cooler Tower');
INSERT INTO product (id, description) VALUES (45, 'PC Case Mid-Tower');
INSERT INTO product (id, description) VALUES (46, 'Power Supply 750W');
INSERT INTO product (id, description) VALUES (47, 'Motherboard ATX');
INSERT INTO product (id, description) VALUES (48, 'Case Fan RGB 120mm');
INSERT INTO product (id, description) VALUES (49, 'Thermal Pad Set');
INSERT INTO product (id, description) VALUES (50, 'VGA to HDMI Adapter');
INSERT INTO product (id, description) VALUES (51, 'DisplayPort Cable');
INSERT INTO product (id, description) VALUES (52, 'Docking Station USB-C');
INSERT INTO product (id, description) VALUES (53, 'Portable Monitor 15-inch');
INSERT INTO product (id, description) VALUES (54, 'Drawing Tablet');
INSERT INTO product (id, description) VALUES (55, 'Document Scanner');
INSERT INTO product (id, description) VALUES (56, 'Label Printer');
INSERT INTO product (id, description) VALUES (57, 'Paper Shredder');
INSERT INTO product (id, description) VALUES (58, 'Wireless Keyboard Compact');
INSERT INTO product (id, description) VALUES (59, 'Trackball Mouse');
INSERT INTO product (id, description) VALUES (60, 'KVM Switch 2-Port');
INSERT INTO product (id, description) VALUES (61, 'Thunderbolt Cable');
INSERT INTO product (id, description) VALUES (62, 'SD Card Reader');
INSERT INTO product (id, description) VALUES (63, 'MicroSD Card 256GB');
INSERT INTO product (id, description) VALUES (64, 'USB Flash Drive 128GB');
INSERT INTO product (id, description) VALUES (65, 'External HDD 4TB');
INSERT INTO product (id, description) VALUES (66, 'NAS Storage 2-Bay');
INSERT INTO product (id, description) VALUES (67, 'Raspberry Pi 5');
INSERT INTO product (id, description) VALUES (68, 'Arduino Starter Kit');
INSERT INTO product (id, description) VALUES (69, 'Soldering Iron Station');
INSERT INTO product (id, description) VALUES (70, 'Multimeter Digital');
INSERT INTO product (id, description) VALUES (71, 'Cable Tester RJ45');
INSERT INTO product (id, description) VALUES (72, 'Crimping Tool');
INSERT INTO product (id, description) VALUES (73, 'Heat Shrink Tubing');
INSERT INTO product (id, description) VALUES (74, 'LED Strip RGB 5m');
INSERT INTO product (id, description) VALUES (75, 'Smart Plug Wi-Fi');
INSERT INTO product (id, description) VALUES (76, 'Smart Bulb E27');
INSERT INTO product (id, description) VALUES (77, 'Security Camera Indoor');
INSERT INTO product (id, description) VALUES (78, 'Doorbell Camera');
INSERT INTO product (id, description) VALUES (79, 'Motion Sensor');
INSERT INTO product (id, description) VALUES (80, 'Temperature Sensor');
INSERT INTO product (id, description) VALUES (81, 'Smoke Detector Smart');
INSERT INTO product (id, description) VALUES (82, 'Air Quality Monitor');
INSERT INTO product (id, description) VALUES (83, 'Desk Fan USB');
INSERT INTO product (id, description) VALUES (84, 'Humidifier Desktop');
INSERT INTO product (id, description) VALUES (85, 'Noise Machine White');
INSERT INTO product (id, description) VALUES (86, 'Footrest Ergonomic');
INSERT INTO product (id, description) VALUES (87, 'Back Support Cushion');
INSERT INTO product (id, description) VALUES (88, 'Blue Light Glasses');
INSERT INTO product (id, description) VALUES (89, 'Desk Organizer');
INSERT INTO product (id, description) VALUES (90, 'Whiteboard Magnetic');
INSERT INTO product (id, description) VALUES (91, 'Sticky Notes Pack');
INSERT INTO product (id, description) VALUES (92, 'Dry Erase Markers');
INSERT INTO product (id, description) VALUES (93, 'Notebook A5 Lined');
INSERT INTO product (id, description) VALUES (94, 'Pen Set Ballpoint');
INSERT INTO product (id, description) VALUES (95, 'Desk Clock Digital');
INSERT INTO product (id, description) VALUES (96, 'Coaster Set Cork');
INSERT INTO product (id, description) VALUES (97, 'Water Bottle Insulated');
INSERT INTO product (id, description) VALUES (98, 'Coffee Mug Ceramic');
INSERT INTO product (id, description) VALUES (99, 'Plant Pot Desktop');
INSERT INTO product (id, description) VALUES (100, 'Stress Ball Set');

-- Order-Product relationships (each order gets 1-4 random products)
INSERT INTO order_product (order_id, product_id) VALUES (1, 3);
INSERT INTO order_product (order_id, product_id) VALUES (1, 15);
INSERT INTO order_product (order_id, product_id) VALUES (1, 7);
INSERT INTO order_product (order_id, product_id) VALUES (2, 1);
INSERT INTO order_product (order_id, product_id) VALUES (2, 15);
INSERT INTO order_product (order_id, product_id) VALUES (2, 22);
INSERT INTO order_product (order_id, product_id) VALUES (3, 41);
INSERT INTO order_product (order_id, product_id) VALUES (3, 42);
INSERT INTO order_product (order_id, product_id) VALUES (4, 5);
INSERT INTO order_product (order_id, product_id) VALUES (4, 6);
INSERT INTO order_product (order_id, product_id) VALUES (4, 20);
INSERT INTO order_product (order_id, product_id) VALUES (5, 18);
INSERT INTO order_product (order_id, product_id) VALUES (5, 19);
INSERT INTO order_product (order_id, product_id) VALUES (6, 34);
INSERT INTO order_product (order_id, product_id) VALUES (7, 9);
INSERT INTO order_product (order_id, product_id) VALUES (7, 43);
INSERT INTO order_product (order_id, product_id) VALUES (8, 11);
INSERT INTO order_product (order_id, product_id) VALUES (8, 12);
INSERT INTO order_product (order_id, product_id) VALUES (9, 25);
INSERT INTO order_product (order_id, product_id) VALUES (9, 29);
INSERT INTO order_product (order_id, product_id) VALUES (9, 30);
INSERT INTO order_product (order_id, product_id) VALUES (10, 67);
INSERT INTO order_product (order_id, product_id) VALUES (10, 68);
INSERT INTO order_product (order_id, product_id) VALUES (10, 69);
INSERT INTO order_product (order_id, product_id) VALUES (11, 75);
INSERT INTO order_product (order_id, product_id) VALUES (11, 76);
INSERT INTO order_product (order_id, product_id) VALUES (12, 88);
INSERT INTO order_product (order_id, product_id) VALUES (12, 17);
INSERT INTO order_product (order_id, product_id) VALUES (13, 93);
INSERT INTO order_product (order_id, product_id) VALUES (13, 94);
INSERT INTO order_product (order_id, product_id) VALUES (14, 36);
INSERT INTO order_product (order_id, product_id) VALUES (14, 37);
INSERT INTO order_product (order_id, product_id) VALUES (15, 53);
INSERT INTO order_product (order_id, product_id) VALUES (15, 52);
INSERT INTO order_product (order_id, product_id) VALUES (16, 2);
INSERT INTO order_product (order_id, product_id) VALUES (16, 10);
INSERT INTO order_product (order_id, product_id) VALUES (17, 97);
INSERT INTO order_product (order_id, product_id) VALUES (17, 98);
INSERT INTO order_product (order_id, product_id) VALUES (18, 44);
INSERT INTO order_product (order_id, product_id) VALUES (18, 45);
INSERT INTO order_product (order_id, product_id) VALUES (18, 46);
INSERT INTO order_product (order_id, product_id) VALUES (19, 83);
INSERT INTO order_product (order_id, product_id) VALUES (19, 84);
INSERT INTO order_product (order_id, product_id) VALUES (20, 55);
INSERT INTO order_product (order_id, product_id) VALUES (20, 56);

-- Reset product sequence
SELECT setval('product_id_seq', (SELECT MAX(id) FROM product));
