apiVersion: v1
kind: Secret
metadata:
  name: store-secrets
  namespace: staging
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: store_staging
  SPRING_DATASOURCE_PASSWORD: staging_pass
  APP_SECURITY_API_KEY: MkT9W9wcuCWObZT9p9NkH1pnGfBpEY9YRM2owOn6JVw=
